apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-service
  namespace: backend
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/backend_service
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      interval: 1m