apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-service
  namespace: backend
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/backend_service
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      interval: 1m
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   annotations:
#     fluxcd.io/automated: "true"
#   name: backend-service
#   namespace: backend
# spec:
#   releaseName: backend-service
#   chart:
#     git: git@github.com:luisbattle/helm-charts.git
#     path: charts/backend_service
#     ref: main