apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-service
  namespace: frontend
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/frontend_service
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: frontend
      interval: 1m
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   annotations:
#     fluxcd.io/automated: "true"
#   name: frontend-service
#   namespace: frontend
# spec:
#   releaseName: frontend-service
#   chart:
#     git: git@github.com:luisbattle/helm-charts.git
#     path: charts/frontend_service
#     ref: main