apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-service
  namespace: frontend
spec:
  interval: 2m
  chart:
    spec:
      chart: charts/frontend_service
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      interval: 2m